name: Required Cypress Component Tests
on:
  pull_request:
    branches:
      - 'master'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.7
        with:
          start: npm start
          browser: chrome
          component: true
          auto-cancel-after-failures: 1
      #- name: Comment Coverage
      #  uses: Tintef/nyc-reporter-action@0.1.0
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #    REPORTER: 'text-summary'
      
      - name: Code coverage-reporter
        # You may pin to the exact commit or the version.
        # uses: tj-actions/coverage-reporter@3eef0fe5e5d3881cc8faa2fb1365296edbf8af60
        uses: tj-actions/coverage-reporter@v5.1
        with:
          # GITHUB_TOKEN or a Repo scoped PAT
          token: ${{ secrets.TOKEN }}
          # Specify a coverage command to run the test.
          coverage-command: "npx nyc report --reporter=text-summary"
        
