name: Required Cypress Component Tests
on:
  pull_request:
    branches:
      - 'master'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.7
        with:
          start: npm run dev
          browser: chrome
          component: true
